global using practice.domain.Entities;
global using practice.domain.Repositories;
global using practice.domain.Kernel.Events;
global using practice.api.Applications.Commands;
global using practice.infrastructure;
global using practice.infrastructure.Data;
global using practice.infrastructure.Repositories;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;